INSERT INTO news (id, newsdate, source, homepage, arts, business, politics, technology, sports, world)
VALUES ('1',
        '2023-07-31',
        'The New York Times',
        'AM homepage content from DB',
        'AM arts content from DB',
        'AM business content from DB',
        'AM politics content from DB',
        'AM technology content from DB',
        'AM sports content from DB',
        'AM world content from DB'),
        ('2',
        '2023-08-06',
        'The New York Times',
        'PM homepage content from DB',
        'PM arts content from DB',
        'PM business content from DB',
        NULL,
        'PM technology content from DB',
        'PM sports content from DB',
        'PM world content from DB'),
        ('3',
        '2023-08-07',
        'The New York Times',
        '',
        '',
        '',
        '',
        '',
        '',
        '');